config/routes.rb
PROTOCOL = Rails.env == 'development' || Rails.env == 'heroku_staging' ? 'http://' : 'https://'

ImpactDialing::Application.routes.draw do
  root :to => "home#index"

  ['monitor', 'how_were_different', 'pricing', 'contact', 'policies'].each do |path|
    match "/#{path}", :to => "home##{path}", :as => path
  end
  match '/client/policies', :to => 'client#policies', :as => :client_policies
  match '/broadcast/policies', :to => 'broadcast#policies', :as => :broadcast_policies
  match '/homecss/css/style.css', :to => 'home#homecss'
  
  namespace 'api' do
    resources :leads
    resources :callers
  end

  namespace 'admin' do
    [:campaigns, :scripts, :callers].each do |entities|
      resources entities, :only => [:index] do
        put '/restore', :controller => entities, :action => 'restore', :as => 'restore'
      end
    end
  end

  namespace "callers" do
    resources :campaigns do
      member do
        post :callin
        match :caller_ready
      end
    end
  end

  resources :caller, :protocol => PROTOCOL, :only => [:index] do
    collection do
      get :login
      post :end_session
      post :phones_only
    end

    member do
      post :assign_campaign
      post :pause
      post :active_session
      post :preview_voter
      post :skip_voter
      post :call_voter
      post :stop_calling
      post :start_calling
      post :gather_response
      post :choose_voter
      post :phones_only_progressive
      post :choose_instructions_option
      post :check_reassign
      post :kick_caller_off_conference
      post :new_campaign_response_panel
      post :transfer_panel
    end

  end

  post :receive_call, :to => 'callin#create', :protocol => PROTOCOL
  post :end_caller_session, :to =>'caller/end_session'
  post :identify_caller, :to => 'callin#identify', :protocol => PROTOCOL
  get :hold_call, :to => 'callin#hold', :protocol => PROTOCOL

  #broadcast
  scope 'broadcast', :protocol => PROTOCOL do
    resources :campaigns do
      member do
        post :verify_callerid
        post :start
        post :stop
        get :dial_statistics
      end
      collection do
        get :control
        get :running_status
      end
      resources :voter_lists, :except => [:new, :show] do
        collection do 
           post :import 
        end
      end
    end
    resources :reports, :protocol => PROTOCOL do
      collection do
        get :usage
        get :dials
        post :dial_details
        post :download
        get :answers
      end
    end
    get '/deleted_campaigns', :to => 'broadcast/campaigns#deleted', :as => :broadcast_deleted_campaigns
    resources :scripts
    resources :messages
    match 'monitor', :to => 'monitor#index'
    match '/', :to => 'broadcast#index', :as => 'broadcast_root'
    match '/login', :to => 'broadcast#login', :as => 'broadcast_login'
  end

  namespace 'broadcast' do
    resources :campaigns, :only => [:show, :index]
  end

  namespace 'client' do
    [:campaigns, :scripts, :callers].each do |type_plural|
      get "/deleted_#{type_plural}", :to => "#{type_plural}#deleted", :as => "deleted_#{type_plural}"
      resources type_plural, :only => [:new, :index, :show, :destroy, :create, :update] do
        put 'restore', :to => "#{type_plural}#restore"
      end
    end
    resources :callers do
      member{ get :reassign_to_campaign }
    end
    resources :campaigns, :only => [] do
      resources :reports do
        collection do
          get :download_report
          post :download
        end
      end
    end
    resource :account, :only => [:show, :create]
    resources :reports do
      collection do
        get :usage
        get :answer
        get :dials
      end
    end
    get :update_report_real
    resources :users, :only => [:create, :destroy]
    post 'user_invite', :to => 'users#invite', :as => 'user_invite'
  end

  scope 'client' do
    match '/', :to => 'client#index', :as => 'client_root'
    resources :campaigns, :only => [] do
      member { post :verify_callerid }
      resources :voter_lists, :except => [:new, :show, :index], :name_prefix => 'client' do
        collection { post :import }
      end
    end
    resources :blocked_numbers, :only => [:index, :create, :destroy]
    resources :monitors do
      collection do
        get :start
        get :stop
        get :deactivate_session
        get :switch_mode
        get :monitor_session
      end
      match "toggle_call_recording" => "monitors#toggle_call_recording"
    end
  end

  scope 'caller' do
    match '/', :to => 'caller#index', :as => 'caller_root'
    match 'logout', :to => 'caller#logout', :as => 'caller_logout'
  end

  resources :campaigns, :path_prefix => 'client', :only => [] do
    member { post :verify_callerid }
    resources :voter_lists, :collection => {:import => :post}, :except => [:new, :show], :name_prefix => 'client'
    match 'clear_calls', :to => 'client/campaigns#clear_calls', :as => 'clear_calls'
  end

  resources :call_attempts, :protocol => PROTOCOL, :only => [:create, :update] do
    member do
      post :connect
      post :end
      post :disconnect
      post :voter_response
      post :hangup
    end
  end
  
  resources :transfer, :protocol => PROTOCOL do
    member do
      post :connect
      post :end
      post :disconnect      
    end
    collection do 
      post :callee
      post :caller            
      post :dial
    end
  end
  

  resources :users do
    put '/update_password', :to => 'client/users#update_password', :as => 'update_password'
  end

  get '/reset_password', :to => 'client/users#reset_password', :as => 'reset_password'

  match '/client/login', :to => 'client#login', :as => :login
  match '/caller/login', :to => 'caller#login', :as => :caller_login

  match '/client/reports', :to => 'client#reports', :as => 'report', :protocol => PROTOCOL
  match '/twilio_callback', :to => 'twilio#callback', :as => :twilio_callback, :protocol => PROTOCOL
  match '/twilio_report_error', :to => 'twilio#report_error', :as => :twilio_report_error, :protocol => PROTOCOL
  match '/twilio_call_ended', :to => 'twilio#call_ended', :as => :twilio_call_ended, :protocol => PROTOCOL

  get 'admin/status', :to => 'admin#state'

  resource :call_attempts, :only => :create

  match ':controller/:action/:id'
  match ':controller/:action'
end

app/models/script.rb
class Script < ActiveRecord::Base

  include Deletable
  validates_presence_of :name, :on => :create, :message => "can't be blank"
  belongs_to :account
  has_many :robo_recordings
  has_many :questions
  has_many :notes
  has_many :transfers
  accepts_nested_attributes_for :questions, :allow_destroy => true
  accepts_nested_attributes_for :notes, :allow_destroy => true
  accepts_nested_attributes_for :transfers, :allow_destroy => true
  accepts_nested_attributes_for :robo_recordings, :allow_destroy => true

  default_scope :order => :name

  scope :robo, :conditions => {:robo => true }
  scope :manual, :conditions => {:robo => false }
  scope :active, {:conditions => {:active => 1}}
  scope :interactive, robo.where("for_voicemail is NULL or for_voicemail = #{false}")
  scope :message, robo.where(:for_voicemail => true)

  after_find :set_result_set

  cattr_reader :per_page
  @@per_page = 25

  def set_result_set
    if self.result_set_1.blank?
      json={}
      for i in 1..49 do
        json["keypad_#{i}"] = self.send("keypad_#{i}")
      end
      self.result_set_1 = json.to_json
    end
  end
  
  def selected_fields
    JSON.parse(voter_fields).select{ |field| VoterList::VOTER_DATA_COLUMNS.values.include?(field) } if voter_fields
  end
  
  def selected_custom_fields
    JSON.parse(voter_fields).select{ |field| !VoterList::VOTER_DATA_COLUMNS.values.include?(field) } if voter_fields
  end
  
  def selected_fields_json
    result = Hash.new
    selected_fields.try(:each) do |x|
      result[x+"_flag"] = true
    end
    result
  end    

  
    def self.default_script(account)
      @rs={
        'keypad_1' => 'Strong supportive',
        'keypad_2' => 'Lean supportive',
        'keypad_3' => 'Undecided',
        'keypad_4' => 'Lean opposed',
        'keypad_5' => 'Strong opposed',
        'keypad_6' => 'Refused',
        'keypad_7' => 'Not home/call back',
        'keypad_8' => 'Language barrier',
        'keypad_9' => 'Wrong number',
        'name' => 'How supportive was the voter?'
      }
      
      possible_responses = []
      possible_responses << PossibleResponse.new(keypad: 1, value:"It's great.", retry: false)
      possible_responses << PossibleResponse.new(keypad: 2, value: "It's amazing!", retry: false)
      possible_responses << PossibleResponse.new(keypad: 3, value: "I'm a bit confused, so I'm going to call Support.", retry: false)
      possible_responses << PossibleResponse.new(keypad: 4, value: "How did I get here? I'm so lost.", retry: false)
      question = Question.new(text: "How do you like the predictive dialer so far?")
      question.possible_responses = possible_responses
      Script.new(name: 'Demo script',  active: 1, account_id: account.id, result_set_1: @rs.to_json).tap do |script|
        script.voter_fields='["FirstName","LastName","Phone"]'
        script.notes << Note.new(note:"What's your favorite feature?")
        script.questions << question
        script.script = <<-EOS
  Hi, I'm calling to tell you about how great Impact Dialing is. 
        EOS
      end
    end

    def questions_and_responses
      questions.all(:include => [:possible_responses]).inject({}) do |acc, question|
        acc[question.text] = question.possible_responses.map(&:value)
        acc
      end
    end
  
end

app/controllers/admin/scripts_controller.rb
module Admin
  class ScriptsController < AdminController
    def index
      @scripts = Script.by_updated.paginate(:per_page => 25, :page => params[:page])
    end

    def restore
      Script.find(params[:script_id]).tap do |c|
        c.restore
        c.save
      end
      redirect_to admin_scripts_path
    end
  end
end

app/controllers/client/scripts_controller.rb
module Client
  class ScriptsController < ::ScriptsController
    skip_before_filter :load_script, :apply_changes

    layout 'client'

    def deleted
      render 'scripts/deleted'
    end

    def index
      @scripts = @user.scripts.manual.active.paginate(:page => params[:page])
    end

    def new
      @script = Script.new(:robo => false, questions: [Question.new(possible_responses: [PossibleResponse.new])])
      @voter_fields = VoterList::VOTER_DATA_COLUMNS.values
      @voter_fields.concat(@user.account.custom_voter_fields.collect{ |field| field.name})
      @voter_field_values=[]
    end

    def create
      params[:script][:voter_fields] =  params[:voter_field] ? params[:voter_field].to_json : nil
      @script = Script.new(params[:script])
      @voter_fields = Voter.upload_fields
      @voter_field_values = params[:voter_field] || []
      if @script.save
        @user.account.scripts << @script
        flash_message(:notice, "Script saved")
        redirect_to :action=>"index"
      else
        render :action=>"new"
      end
    end

    def show
      @script = @user.account.scripts.find(params[:id])
      @script.questions << [Question.new(possible_responses: [PossibleResponse.new])]  if @script.questions.empty?
      #@voter_fields = ["CustomID","FirstName","MiddleName","LastName","Suffix","Address","City","State/Province","Zip/Postal Code","Country","Phone","Email"]
      @voter_fields = VoterList::VOTER_DATA_COLUMNS.values
      @voter_fields.concat(@user.account.custom_voter_fields.collect{ |field| field.name})
      if @script.voter_fields!=nil
        begin
          @voter_field_values = JSON.parse(@script.voter_fields)
        rescue
          @voter_field_values=[]
        end
      else
        @voter_field_values=[]
      end
    end

    def update
      params[:script][:voter_fields] =  params[:voter_field] ? params[:voter_field].to_json : nil
      begin
        params[:save_as] ? save_as : @script = account.scripts.find_by_id(params[:id])

        if params[:save_as]
          redirect_to client_script_path(@script)
        elsif !params[:save_as] && @script.update_attributes(params[:script])
          flash_message(:notice, "Script updated")
          redirect_to :action=>"index"
        else
          render :action=>"new"
        end
      rescue Exception => e
        flash_message(:notice, "Script not saved. Error:" + e.message)
        render :action=>"new"
      end
    end

    def destroy
      @script = @user.account.scripts.manual.find(params[:id])
      @script.update_attributes(:active => false)
      flash_message(:notice, "Script deleted")
      redirect_to :action => "index"
    end

    private

    def save_as
      @script = Script.new(:name => "", :active => true, :account => @user.account, :script => params[:script][:script], :voter_fields => params[:script][:voter_fields])
      @script.save(:validate => false)
      params[:script][:questions_attributes].each_value.each do |q|
        if q[:_destroy] == "false"
          question = @script.questions.new(:text => q[:text])
          question.save!
          q[:possible_responses_attributes].each_value.each do |ps|
            if ps[:_destroy] == "false"
              possible_response = question.possible_responses.new(:value => ps[:value], :keypad => ps[:keypad], :retry => ps[:retry])
              possible_response.save!
            end
          end
        end
      end
      params[:script][:notes_attributes].try(:each_value).try(:each) do |n|
        if n[:_destroy] == "false"
          note = @script.notes.new(:note => n[:note])
          note.save!
        end
      end
    end

  end
end

app/controllers/scripts_controller.rb
class ScriptsController < ClientController
  layout 'v2'
  include DeletableController

  before_filter :new_script, :only => [:new, :create]
  before_filter :load_script, :only => [:update, :show, :destroy, :edit]
  before_filter :apply_changes, :only => [:create, :update]

  def type_name
    'script'
  end

  def load_script
    @script = Script.find(params[:id])
  end

  def index
  @scripts = @user.account.scripts.active.robo.paginate(:page => params[:page])
  end

  def new_script
    @fields = ["CustomID", "FirstName", "MiddleName", "LastName", "Suffix", "Age", "Gender", "Phone", "Email"]
    @breadcrumb=[{"Scripts"=>"/client/scripts"}, "Add Script"]
    @label = 'New Script'
    @script = @user.account.scripts.new(:name => 'Untitled Script', :robo=>true)
    @incompletes = {}
    @voter_fields = []
    @numResults = 1
    @numNotes = 0
  end

  def new
    @script.robo_recordings.build
  end

  def create
    #before filter apply_changes triggered here
  end

  def update
    #before filter apply_changes triggered here
  end

  def apply_changes
    @script.update_attributes(params[:script])
    numResults = params[:numResults]
    for r in 1..numResults.to_i do

      for i in 1..99 do
        this_keypadval = params["keypad_#{r}_#{i}"]
        if !this_keypadval.blank? && !isnumber(this_keypadval)
          flash_now(:error, "Keypad value for call results #{r} entered '#{this_keypadval}' must be numeric")
          return
        end
      end

      this_results={}
      for i in 1..99 do
        this_result = params["text_#{r}_#{i}"]
        this_keypadval = params["keypad_#{r}_#{i}"]
        if !this_result.blank? && !this_keypadval.blank?
          this_results["keypad_#{i}"] = this_result
        else
          this_results["keypad_#{i}"] = nil
        end
      end
      logger.info "Done with #{r}: #{this_results.inspect}"
      @script.attributes = {"result_set_#{r}" => this_results.to_json}
    end

    for i in 1..NUM_RESULT_FIELDS do
      this_note = params["note_#{i}"]
      @script.attributes = {"note_#{i}" => this_note.blank? ? nil : this_note}
    end

    all_incompletes={}
    for i in 1..NUM_RESULT_FIELDS do
      all_incompletes[i] = params["incomplete_#{i}_"] || []
    end

    @script.incompletes = all_incompletes.to_json

    if @script.valid?
      @script.voter_fields = params[:voter_field] ? params[:voter_field].to_json : nil

      @script.save
      flash_message(:notice, "Script saved")
      redirect_to @script
    else
      render :action => 'new'
    end
  end

  def show
    @fields = ["CustomID", "FirstName", "MiddleName", "LastName", "Suffix", "Age", "Gender", "Phone", "Email"]
    @breadcrumb=[{"Scripts"=>"/client/scripts"}, "Edit Script"]
    @label = "Add script"

    @numResults = 0
    for i in 1..NUM_RESULT_FIELDS do
      @numResults+=1 if !eval("@script.result_set_#{i}").blank?
    end
    @numNotes = 0
    for i in 1..NUM_RESULT_FIELDS do
      @numNotes+=1 if !eval("@script.note_#{i}").blank?
    end

    if @script.incompletes!=nil
      begin
        @incompletes = JSON.parse(@script.incompletes)
      rescue
        @incompletes={}
      end
    else
      @incompletes={}
    end

    if @script.voter_fields!=nil
      begin
        @voter_fields = eval(@script.voter_fields)
      rescue
        @voter_fields=[]
      end
    else
      @voter_fields=[]
    end
    render :template => 'scripts/new'
  end
end

app/views/scripts/_messages.html.erb
<%messages||=[] %>
<% if messages.length==0 %>
    <div class="form">
      <label>No messages entered.</label>
    </div>
<% else %>
    <div class="table">
      <table>
        <tr>
          <th>Name</th>
          <th>Date added</th>
          <th width="55" class="ac"></th>
        </tr>
        <% messages.each do |c| %>
            <tr class="<%= cycle("odd","even") %>">
              <td><h3><%= link_to c.name, c.for_voicemail? ? message_path(c) : script_path(c) %></h3></td>
              <td><%= c.created_at.strftime("%m/%d/%Y") %></td>
              <td><a href="javascript:if(<%=messages.try(:length) %>== 1) alert('You must have at least one script.'); else if(confirm('Are you sure you want to delete this script?')) document.location.href='/client/script_delete/<%= c.id %>';" class="ico del">Delete</a>
              </td>
            </tr>
        <% end %>

      </table>
    </div>

    <p><%= page_entries_info messages %> <%= will_paginate messages %></p>

<% end %>

app/views/scripts/_recording_response_fields.html.erb
<!--DO NOT EDIT-->
<table class="fields">
  <tr>
    <td width="30%"><%= f.text_field :response %></td>
    <td width="30%"><%= f.text_field :keypad %></td>
    <td><%= f.link_to_remove "Remove", :class => "ico del" %></td>
  </tr>
</table>

<!--DO NOT EDIT-->

app/views/scripts/_robo_recording_fields.html.erb
<div class="fields">
  <fieldset>
    <legend>Recording</legend>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <fieldset>
      <legend>Audio</legend>

      <% if f.object.file.exists? %>
          <div>
            <embed type="application/x-shockwave-flash" wmode="transparent" height="27" width="320"
                   src="http://www.google.com/reader/ui/3523697345-audio-player.swf?audioUrl=<%= f.object.file.url %>"/>
          </div>
      <% end %>
      <p>You can upload an MP3, WAV, or AIFF file, although you can only preview MP3 files.</p>
      <p><%= f.file_field :file %></p>
    </fieldset>
    <!--DO NOT EDIT-->
    <fieldset>
      <legend>Responses</legend>
      <div class="fields">
        <table class="fields">
          <tr>
            <th width="30%">Response</th>
            <th width="30%">Keypad</th>
            <th>Delete</th>
          </tr>
        </table>
      </div>

      <%= f.fields_for :recording_responses do |response_form| %>
          <%= render :partial=>"recording_response_fields", :locals => {:f => response_form} %>
      <% end %>
      <%= f.link_to_add "Add response", :recording_responses, :class => "action secondary small_font" %>
    </fieldset>

    <p class="actions"><%= f.link_to_remove "Remove this recording", :class => "action secondary" %></p>
    <!--DO NOT EDIT-->
  </fieldset>
</div>

app/views/scripts/deleted.html.erb
<h1>Deleted scripts</h1>
<% if @scripts.length==0 %>
  <div class="form">
    <label>No scripts entered.</label>
  </div>
<% else %>
  <div class="table">
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <th>Name</th>
        <th>Date added</th>
        <th>Date deleted</th>
        <th width="55" class="ac"></th>
      </tr>
      <% @scripts.each do |s| %>
        <tr class="<%= cycle("odd","even") %>">
          <td><strong><a href="/client/script_add/<%= s.id %>"><%= s.name %></a></strong></td>
          <td><%= s.created_at.strftime("%m/%d/%Y") %></td>
          <td><%= s.updated_at.strftime("%m/%d/%Y") %></td>
          <td>
            <%= form_tag(client_script_restore_path(s), :id => "restore-script#{s.id}-form", :method => :put) do |f| %>
              <%= link_to 'Restore', 'javascript:void(0)', :onclick => "$('#restore-script#{s.id}-form').submit()" %>
            <% end %>
          </td>
        </tr>
      <% end %>

    </table>
  </div>


  <!-- New HTML -->
  <p><%= page_entries_info @scripts %> <%= will_paginate @scripts %></p>
  <!-- / New HTML -->

  <!-- Table -->
<% end %>
<p class="actions"><%= link_to 'Return to active scripts', '/client/scripts', :class => 'action primary' %></p>

app/views/scripts/index.html.erb
<h1>Messages</h1>
<%= render 'messages', :messages => @scripts  %>
<p class="actions"><%= link_to 'Add new message', new_message_path, :class => 'action primary' %></p>
<p class="actions"><%= link_to 'Add interactive message', new_script_path, :class => 'action primary' %></p>
<p class="actions"><%= link_to 'View deleted messages', client_deleted_scripts_path, :class => 'action secondary' %></p>

app/views/scripts/new.html.erb
<h1><%= @script.new_record? ? "New message" : "Edit message" %></h1>
<%= error_messages_for :script %>

<%= nested_form_for @script, :html => {:name => 'callerForm', :id => 'callerForm', :multipart => true} do |f| %>
    <%= f.hidden_field :robo %>
    <p>
      <label>Message name</label>
      <%= f.text_field :name, {:class => "field"} %>
    </p>
    <%= f.fields_for :robo_recordings do |recording| %>
        <%= render :partial => "robo_recording_fields", :locals => {:f => recording} %>
    <% end %>
    
    <%= f.link_to_add "Add recording", :robo_recordings, :class => "action secondary small_font" %>
    <p>&nbsp;</p>
    
    <div class="buttons"><%= button_tag 'Save' %></div>
<% end %>