config/routes.rb
PROTOCOL = Rails.env == 'development' || Rails.env == 'heroku_staging' ? 'http://' : 'https://'

ImpactDialing::Application.routes.draw do
  root :to => "home#index"

  ['monitor', 'how_were_different', 'pricing', 'contact', 'policies'].each do |path|
    match "/#{path}", :to => "home##{path}", :as => path
  end
  match '/client/policies', :to => 'client#policies', :as => :client_policies
  match '/broadcast/policies', :to => 'broadcast#policies', :as => :broadcast_policies
  match '/homecss/css/style.css', :to => 'home#homecss'
  
  namespace 'api' do
    resources :leads
    resources :callers
  end

  namespace 'admin' do
    [:campaigns, :scripts, :callers].each do |entities|
      resources entities, :only => [:index] do
        put '/restore', :controller => entities, :action => 'restore', :as => 'restore'
      end
    end
  end

  namespace "callers" do
    resources :campaigns do
      member do
        post :callin
        match :caller_ready
      end
    end
  end

  resources :caller, :protocol => PROTOCOL, :only => [:index] do
    collection do
      get :login
      post :end_session
      post :phones_only
    end

    member do
      post :assign_campaign
      post :pause
      post :active_session
      post :preview_voter
      post :skip_voter
      post :call_voter
      post :stop_calling
      post :start_calling
      post :gather_response
      post :choose_voter
      post :phones_only_progressive
      post :choose_instructions_option
      post :check_reassign
      post :kick_caller_off_conference
      post :new_campaign_response_panel
      post :transfer_panel
    end

  end

  post :receive_call, :to => 'callin#create', :protocol => PROTOCOL
  post :end_caller_session, :to =>'caller/end_session'
  post :identify_caller, :to => 'callin#identify', :protocol => PROTOCOL
  get :hold_call, :to => 'callin#hold', :protocol => PROTOCOL

  #broadcast
  scope 'broadcast', :protocol => PROTOCOL do
    resources :campaigns do
      member do
        post :verify_callerid
        post :start
        post :stop
        get :dial_statistics
      end
      collection do
        get :control
        get :running_status
      end
      resources :voter_lists, :except => [:new, :show] do
        collection do 
           post :import 
        end
      end
    end
    resources :reports, :protocol => PROTOCOL do
      collection do
        get :usage
        get :dials
        post :dial_details
        post :download
        get :answers
      end
    end
    get '/deleted_campaigns', :to => 'broadcast/campaigns#deleted', :as => :broadcast_deleted_campaigns
    resources :scripts
    resources :messages
    match 'monitor', :to => 'monitor#index'
    match '/', :to => 'broadcast#index', :as => 'broadcast_root'
    match '/login', :to => 'broadcast#login', :as => 'broadcast_login'
  end

  namespace 'broadcast' do
    resources :campaigns, :only => [:show, :index]
  end

  namespace 'client' do
    [:campaigns, :scripts, :callers].each do |type_plural|
      get "/deleted_#{type_plural}", :to => "#{type_plural}#deleted", :as => "deleted_#{type_plural}"
      resources type_plural, :only => [:new, :index, :show, :destroy, :create, :update] do
        put 'restore', :to => "#{type_plural}#restore"
      end
    end
    resources :callers do
      member{ get :reassign_to_campaign }
    end
    resources :campaigns, :only => [] do
      resources :reports do
        collection do
          get :download_report
          post :download
        end
      end
    end
    resource :account, :only => [:show, :create]
    resources :reports do
      collection do
        get :usage
        get :answer
        get :dials
      end
    end
    get :update_report_real
    resources :users, :only => [:create, :destroy]
    post 'user_invite', :to => 'users#invite', :as => 'user_invite'
  end

  scope 'client' do
    match '/', :to => 'client#index', :as => 'client_root'
    resources :campaigns, :only => [] do
      member { post :verify_callerid }
      resources :voter_lists, :except => [:new, :show, :index], :name_prefix => 'client' do
        collection { post :import }
      end
    end
    resources :blocked_numbers, :only => [:index, :create, :destroy]
    resources :monitors do
      collection do
        get :start
        get :stop
        get :deactivate_session
        get :switch_mode
        get :monitor_session
      end
      match "toggle_call_recording" => "monitors#toggle_call_recording"
    end
  end

  scope 'caller' do
    match '/', :to => 'caller#index', :as => 'caller_root'
    match 'logout', :to => 'caller#logout', :as => 'caller_logout'
  end

  resources :campaigns, :path_prefix => 'client', :only => [] do
    member { post :verify_callerid }
    resources :voter_lists, :collection => {:import => :post}, :except => [:new, :show], :name_prefix => 'client'
    match 'clear_calls', :to => 'client/campaigns#clear_calls', :as => 'clear_calls'
  end

  resources :call_attempts, :protocol => PROTOCOL, :only => [:create, :update] do
    member do
      post :connect
      post :end
      post :disconnect
      post :voter_response
      post :hangup
    end
  end
  
  resources :transfer, :protocol => PROTOCOL do
    member do
      post :connect
      post :end
      post :disconnect      
    end
    collection do 
      post :callee
      post :caller            
      post :dial
    end
  end
  

  resources :users do
    put '/update_password', :to => 'client/users#update_password', :as => 'update_password'
  end

  get '/reset_password', :to => 'client/users#reset_password', :as => 'reset_password'

  match '/client/login', :to => 'client#login', :as => :login
  match '/caller/login', :to => 'caller#login', :as => :caller_login

  match '/client/reports', :to => 'client#reports', :as => 'report', :protocol => PROTOCOL
  match '/twilio_callback', :to => 'twilio#callback', :as => :twilio_callback, :protocol => PROTOCOL
  match '/twilio_report_error', :to => 'twilio#report_error', :as => :twilio_report_error, :protocol => PROTOCOL
  match '/twilio_call_ended', :to => 'twilio#call_ended', :as => :twilio_call_ended, :protocol => PROTOCOL

  get 'admin/status', :to => 'admin#state'

  resource :call_attempts, :only => :create

  match ':controller/:action/:id'
  match ':controller/:action'
end

app/views/admin/add_cms.html.erb
<center>
<br/>
<br/>
Add CMS block:
<br/>
<b>Version: <% if @version.blank? %>Live<% else %><%= @version %><% end %> (<a href="/admin/pick_version">edit</a>)</b>
<%= form_tag() do %>
<table>
	<tr><td>Key:</td><td> <input type="text" name="key"></td>
	<tr><td valign="top">Content:</td><td> <textarea name="content" rows="10" cols="40"></textarea></td>
</table>
	<input type="submit" value="Submit">
</table>
<% end -%>
</center>

app/views/admin/benchmarking.html.erb
VoterObjects: <%= ObjectSpace.each_object(Voter){} %>
CampaignObjects: <%= ObjectSpace.each_object(Campaign){} %>
CallAttemptsObjets: <%= ObjectSpace.each_object(CallAttempt){} %>
CallerSessionObjets: <%= ObjectSpace.each_object(CallerSession){} %>
AnswerObjets: <%= ObjectSpace.each_object(Answer){} %>
QuestionObjets: <%= ObjectSpace.each_object(Question){} %>
PossibleResponseObjets: <%= ObjectSpace.each_object(PossibleResponse){} %>

Count: <%= ObjectSpace.count_objects %>
Memory <%= (`ps -o rss= -p #{$$}`.to_f / 1024.0) %>

app/views/admin/charge.html.erb
<% if request.post? %>
  <%  if @success %>
    SUCCESS!  <%= @emails %> has been charged <%= params[:tocharge].to_f %>.<br/>
    <%= @response.inspect %>
  <% else %>
    FAILURE!
    <%= @response.inspect %>
  <% end %>
  <br/>
  <a href="/admin/users">Back to user admin</a>
<% else %>
  <% form_tag do |f| %>
    Amount to charge: $<input type="text" name="tocharge">
    <br/> <%= @emails %>
    <%=  submit_tag "Make charge", :disable_with => "Please wait..." %>
  <% end -%>
<% end %>

app/views/admin/cms.html.erb
<center>
	<Br/><Br/>
<b>Page CMS (<a href="/admin/add_cms">add</a>)</b>
<Br/>
<b>Version: <% if @version.blank? %>Live<% else %><%= @version %><% end %> (<a href="/admin/pick_version">edit</a>)</b>
<style>
	table.tt tr td{border:1px dotted #999;}
</style>
<table cellpadding="5" class="tt" >
	<tr>
		<td>key</td>
		<td>content</td>
		<td></td>
	</tr>
	<% @keys.each do |k| %>
		<% 
		defaulted=true
		entry =  Seo.find_by_crmkey_and_active_and_version(k,1,@version, :order=>"crmkey", :conditions=>"controller is NULL") 
		if entry.blank?
			entry =  Seo.find_by_crmkey_and_active_and_version(k,1,nil, :order=>"crmkey", :conditions=>"controller is NULL") 	else
			defaulted=false
		end
		entry =  Seo.find_by_crmkey_and_active(k,1, :order=>"crmkey", :conditions=>"controller is NULL")  if entry.blank?
	%>
		<tr>
			<td><%= k %> <% if defaulted %>(defaulted)<% end %></td>
			<% if defaulted %>
				<td ><div style="overflow:auto;width:400px; height:100px;"><%= h(entry.content) %></div></td>
				<td><a href="/admin/copy_cms/<%= entry.id %>">edit</a></td>
			<% else %>
				<td ><div style="overflow:auto;width:400px; height:100px;"><%= h(entry.content) %></div></td>
				<td><a href="/admin/edit_cms/<%= entry.id %>">edit</a></td>
			<% end %>
		</tr>
	<% end %>
	<!--
	<# @keys.each do |p| %>
		<tr>
			<td><# p.crmkey %></td>
			<td ><div style="overflow:auto;width:400px; height:100px;"><%# p.content %></div></td>
			<td><a href="/admin/edit_cms/<# p.id %>">edit</a></td>
		</tr>
	<# end %>
	-->

</table>
</center>
<br/>

app/views/admin/copy_cms.html.erb
<center>
<br/>
<br/>
Edit CMS block:
<br/>
<b>Version: <% if @version.blank? %>Live<% else %><%= @version %><% end %> (<a href="/admin/pick_version">edit</a>)</b>
<%= form_tag() do %>
<table>
	<tr><td>Key:</td><td> <input type="text" name="key" value="<%= @source.crmkey %>"></td>
	<tr><td valign="top">Content:</td><td> <textarea name="content" rows="10" cols="40"><%= @source.content %></textarea></td>
</table>
	<input type="submit" value="Submit">
</table>
<% end -%>
</center>

app/views/admin/edit_cms.html.erb
<center><%= error_messages_for :seo %>
<br/><br/>
<b>Editing  <%= @seo.crmkey %>
	<br/>
	<b>Version: <% if @version.blank? %>Live<% else %><%= @version %><% end %> (<a href="/admin/pick_version">edit</a>)</b>

	</td>
<%= form_for :seo, @seo do |f| -%>
	<table>
		<tr>
			<td>content:</td>
			<td><%= f.text_area :content %></td>
		</tr>
	</table>
	<%= f.submit "Submit", :disable_with => 'Submiting...' %>
	<input type="button" value="Cancel" onclick="document.location.href='/admin/cms';">
<% end -%>
</center>

app/views/admin/index.html.erb
<ul>
  <li><%= link_to 'Status', admin_status_path %></li>
  <li><%= link_to 'Reports', '/admin/report' %></li>
  <li><%= link_to 'Campaigns', admin_campaigns_path %></li>
  <li><%= link_to 'Callers', admin_callers_path %></li>
  <li><%= link_to 'Scripts', admin_scripts_path %></li>
</ul>

app/views/admin/log.html.erb
<% if params[:id].blank? %>
	<%= form_tag do %>
		Enter call Sid:
  		<input type="textbox" name="id">
		<input type="submit">
	<% end -%>
<% else %>
	<table>
		<tr>
			<td valign="top">
				<table border="1">
					<% @reqs.each do |req| %>
					<tr>
						<td><%= req.url[req.url.index("/callin"),999] %></td>
						<td>
							<%
								begin
									p=YAML.load(req.params )
								rescue
									p=req.params
								end

							%>
							<%if p.class==Hash %>
								<% p.keys.each do |k| %>
								<%= k %>: <%= p[k] %><br/>
								<% end %>
							<% else %>
								<%= p %>
							<% end %>
						</td>
						<td><%= req.first_line %></td>
					</tr>
					<% end %>
				</table>
			</td>
			<td valign="top">

				<% @attempts.each do |a| %>
					<% colour = "%06x" % (rand * 0xffffff) %>
					<table border="1">
					<tr bgcolor="<%= colour %>">
						<td><%= a.id %></td>
						<td><%= a.call_start %></td>
						<td><%= a.call_end %></td>
						<td><%= a.voter.Phone %></td>
					</tr>
					<tr>
						<td colspan="4">
							<table>

								<% attemptreqs=Dump.find_all_by_guid(a.sid, :order=>"first_line") %>
								<% attemptreqs.each do |areq| %>
									<tr bgcolor="<%= colour %>">
										<td><%= areq.url[areq.url.index("/callin"),999] %></td>
										<td>
											<%
												begin
													p=YAML.load(areq.params )
												rescue
													p=areq.params
												end

											%>
											<%if p.class==Hash %>
												<% p.keys.each do |k| %>
												<%= k %>: <%= p[k] %><br/>
												<% end %>
											<% else %>
												<%= p.split(":").collect{|f| "#{f}<br/>" } %>
											<% end %>
										</td>
										<td><%= areq.first_line %></td>
									</tr>
								<% end %>
							</table>
						</td>
					</tr>
				</table>
				<% end %>
			</td>
		</tr>
	</table>

<% end %>

app/views/admin/pick_version.html.erb
<center><Br/>
Select a version:
<%= form_tag do %>
  <select name="v">
	<% @versions.each do |v| %>
		<option name="<%= v %>" <% if session[:cms_version]==v %>selected<% end %>><%= v %><% if v.blank? %>Live<% end %></option>
	<% end %>
	</select>
	<input type="submit" value="Choose Version">
<% end -%>


<br/>or<br/>
<%= form_tag do %>
	Create a new version: <input type="text" name="nv">
	<input type="submit" value="Create Version">
<% end %>
</center>

<br/>

app/views/admin/report.html.erb
<h1>Admin Reporting</h1>

Report Date Range:
<%= form_tag ("/admin/report") do %>
  <table>
    <tr>
      <td>From:</td>
      <td> <%= unobtrusive_date_text_picker_tag :from_date,@from_date %> </td>
    </tr>
    <tr>
      <td>
        To:</td>
      <td>  <%= unobtrusive_date_text_picker_tag :to_date,@to_date %>
        <!--<input type="submit" class="button" value="update" size="4">-->
      </td>
    </tr>
  </table>	<button type="submit">Show results</button>
<% end %>

<br/>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <th>Campaign ID</th>
    <th>Campaign Name</th>
    <th>Account Id</th>
    <th>Agent Call Count</th>
    <th>Agent Minutes</th>
    <th>Agent Twilio Cost</th>
    <th>Call Count</th>
    <th>Call Minutes</th>
    <th>Call Twilio Cost</th>
    <th>Total Minutes</th>
    <th>Total Twilio Cost</th>
  </tr>

  <% @output.each do |r| %>
    <% campaign=r["campaign"] %>
    <% calls=r["calls"] %>
    <% sessions=r["sessions"] %>
    <%
      agent_mins=0
      agent_twilio=0
      call_mins=0
      call_twilio=0
    %>
    <tr class="<%= cycle("odd","even") %>">
      <td><%= campaign[0] %></td>
      <td><%= campaign[1] %></td>
      <td><%= campaign[2] %></td>
      <% sessions.each do |c| %>
        <% agent_mins=c[1] %>
        <% agent_twilio=c[2] %>
        <td><%= c[0] %></td>
        <td><%= agent_mins %></td>
        <td><%=  number_to_currency agent_twilio %></td>
      <% end %>
      <% calls.each do |c| %>
        <% call_mins=c[1] %>
        <% call_twilio=c[2] %>
        <td><%= c[0] %></td>
        <td><%= call_mins %></td>
        <td><%=  number_to_currency call_twilio %></td>
      <% end %>
      <td><%= agent_mins.to_i +  call_mins.to_i%></td>
      <td><%= number_to_currency(agent_twilio.to_f +  call_twilio.to_f)%></td>
    </tr>
  <% end %>
</table>

app/views/admin/state.html.erb
<h1>System Status</h1>
<table>
  <tr>
    <td>Calling Status:</td>
    <td><%= @calling_status %></td>
  </tr>
  <tr>
    <td>Logged in campaigns:</td>
    <td><%= @logged_in_campaigns.length %></td>
  </tr>
  <tr>
    <td>Logged in callers:</td>
    <td><%= @logged_in_callers.length %></td>
  </tr>

    <% @logged_in_campaigns.each do |k| %>
      <tr>
        <td valign="top"><%= k.name %> <a target="_blank" href="/admin/login/<%= k.account.users.first.id %>" style="font-size:9px;">login</a></td>
        <td>
          <%
            callers = CallerSession.find_all_by_campaign_id_and_on_call(k,1)
          %>
          <br/>Callers:
          <ul>
            <% callers.each do |ca| %>
              <li>id <%= ca.id %> <%= ca.caller.name %> <%= ca.caller.email %> started <%= ca.starttime %> from <%= ca.caller_number %> <% if !ca.available_for_call %>Not <% end %>Available <%= link_to 'end call', admin_status_path(:end => ca.id) %>
            <% end %>
          </li>
      </ul>
      <hr/>
    </td>
  </tr>
<% end -%>

</table>

app/views/admin/status.html.erb
<h1>System Status</h1>
<table>
  <tr>
    <td>Calling Status:</td>
    <td><%= @calling_status %></td>
  </tr>
  <tr>
    <td>Logged in campaigns:</td>
    <td><%= @logged_in_campaigns.length %></td>
  </tr>
  <tr>
    <td>Logged in callers:</td>
    <td><%= @logged_in_callers.length %></td>
  </tr>
  <tr>
    <td>Calls in progress:</td>
    <td><%= @all_calls %></td>
    <tr>
      <td>Twilio queued:</td>
      <td>Temporarily disabled</td>
    </tr>
    <tr>
      <td>Stuck dials:</td>
      <td><% if @ready_to_dial.length >7 %> <% @errors= @errors + " #{@ready_to_dial.length} stuck dials" %> <font color="red"><% end %><%= @ready_to_dial.length %></font></td>
    </tr>

    <% @logged_in_campaigns.each do |k| %>
      <tr>
        <td valign="top"><%= k.name %> <a target="_blank" href="/admin/login/<%= k.account.users.first.id %>" style="font-size:9px;">login</a></td>
        <td>
          <%
            stats = k.call_stats(10)
            attempts = stats[:attempts]
            answer_pct = (stats[:answer_pct] * 100).to_i
            abandon_pct = (stats[:abandon_pct] * 100).to_i
            @errors= @errors + " #{k.name} answer_pct #{answer_pct}" if answer_pct<9 && attempts.length > 10
            callers = CallerSession.find_all_by_campaign_id_and_on_call(k,1)
            callers_on_call = CallerSession.find_all_by_campaign_id_and_on_call_and_available_for_call(k,1,0)
            not_on_call = callers.length - callers_on_call.length
            calls = CallAttempt.find_all_by_campaign_id(k, :conditions=>"call_end is NULL")
            voters = k.voters("not called")
            @errors= @errors + " #{k.name} abandon_pct #{abandon_pct}" if abandon_pct>65 && attempts.length > 10
          %>
          Callers logged in: <%= callers.length %>
          <br/>Callers on call: <%= callers_on_call.length %>
          <br/>Callers not on call: <%= not_on_call %>
          <br/>Numbers to call: <%=  voters.length %>
          <br/>Calls in progress: <%= calls.length %>
          <br/><% if answer_pct < 9 %><font color="red"><% end %>Answer pct: <%= answer_pct %>  <% if answer_pct < 9 %></font><% end %>
          <br/>Abandon pct: <%= abandon_pct %>
          <br/>Callers:
          <ul>
            <% callers.each do |ca| %>
              <li>id <%= ca.id %> <%= ca.caller.name %> <%= ca.caller.email %> started <%= ca.starttime %> from <%= ca.caller_number %> <% if !ca.available_for_call %>Not <% end %>Available <a href="/admin/status?end=<%= ca.id %>">end call</a>

                <% if ca.available_for_call %>
                  <% last_attempt = CallAttempt.find_by_caller_session_id(ca.id, :order=>"id desc", :limit=>1)  %>
                  <% if !last_attempt.blank?
                  hold_time  =  (Time.now-last_attempt.call_end).round
                  @errors= @errors + " caller #{ca.id} #{ca.caller.name} hold time #{hold_time}s" if hold_time>180
                %>
                Hold time: <%= hold_time %>s
              <% end %>
            <% end %>
          </li>

        <% end %>
      </ul>
      <hr/>
    </td>
  </tr>
<% end -%>

</table>
<font color="red"><b><%= @errors %></b></font>

<% if @errors.strip!="" && params[:sms]=="1" && Rails.env =="production"
t = TwilioLib.new(TWILIO_ACCOUNT, TWILIO_AUTH)
a=t.call("POST", "SMS/Messages", {'From' => APP_NUMBER, 'To' => "8583829141", 'Body'=>"Alert: #{@errors[0..150]}"})
t = TwilioLib.new(TWILIO_ACCOUNT, TWILIO_AUTH)
a=t.call("POST", "SMS/Messages", {'From' => APP_NUMBER, 'To' => "9165959543", 'Body'=>"Alert: #{@errors[0..150]}"})
end %>

app/views/admin/users.html.erb
<table border="1">
  <tr>
    <td>id</td>
    <td>names</td>
    <td>email</td>
    <td>phone</td>
    <td>created_at</td>
    <td>card_verified</td>
    <td>activated</td>
    <td>domain</td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <% @accounts.each do |account| %>
    <tr>
      <td><%= account.id %></td>
      <td><%= account.users.map{|u| "#{u.fname} #{u.lname}"}.join(', ') %></td>
      <td><%= account.users.map(&:email).join(', ') %></td>
      <td><%= account.users.map(&:phone).join(', ') %></td>
      <td><%= account.created_at %></td>
      <td><%= account.card_verified %> </td>
      <td><%= account.activated %> </td>
      <td><%= account.domain %> </td>
      <td><a href="/admin/toggle_activated/<%= account.id %>">toggle activated</a></td>
      <td><a href="/admin/toggle_card_verified/<%= account.id %>">toggle card verified</a></td>
      <td><a href="/admin/charge/<%= account.id %>">charge</a></td>
      <td><a href="/admin/login/<%= account.users.first.id %>">login</a></td>
			<td><a href="/admin/destroy/<%= account.id %>" onclick="javascript:if(!confirm('Are you sure you want to delete this account?')) return false;">delete</a></td>
    </tr>
  <% end %>
</table>