config/routes.rb
PROTOCOL = Rails.env == 'development' || Rails.env == 'heroku_staging' ? 'http://' : 'https://'

ImpactDialing::Application.routes.draw do
  root :to => "home#index"

  ['monitor', 'how_were_different', 'pricing', 'contact', 'policies'].each do |path|
    match "/#{path}", :to => "home##{path}", :as => path
  end
  match '/client/policies', :to => 'client#policies', :as => :client_policies
  match '/broadcast/policies', :to => 'broadcast#policies', :as => :broadcast_policies
  match '/homecss/css/style.css', :to => 'home#homecss'
  
  namespace 'api' do
    resources :leads
    resources :callers
  end

  namespace 'admin' do
    [:campaigns, :scripts, :callers].each do |entities|
      resources entities, :only => [:index] do
        put '/restore', :controller => entities, :action => 'restore', :as => 'restore'
      end
    end
  end

  namespace "callers" do
    resources :campaigns do
      member do
        post :callin
        match :caller_ready
      end
    end
  end

  resources :caller, :protocol => PROTOCOL, :only => [:index] do
    collection do
      get :login
      post :end_session
      post :phones_only
    end

    member do
      post :assign_campaign
      post :pause
      post :active_session
      post :preview_voter
      post :skip_voter
      post :call_voter
      post :stop_calling
      post :start_calling
      post :gather_response
      post :choose_voter
      post :phones_only_progressive
      post :choose_instructions_option
      post :check_reassign
      post :kick_caller_off_conference
      post :new_campaign_response_panel
      post :transfer_panel
    end

  end

  post :receive_call, :to => 'callin#create', :protocol => PROTOCOL
  post :end_caller_session, :to =>'caller/end_session'
  post :identify_caller, :to => 'callin#identify', :protocol => PROTOCOL
  get :hold_call, :to => 'callin#hold', :protocol => PROTOCOL

  #broadcast
  scope 'broadcast', :protocol => PROTOCOL do
    resources :campaigns do
      member do
        post :verify_callerid
        post :start
        post :stop
        get :dial_statistics
      end
      collection do
        get :control
        get :running_status
      end
      resources :voter_lists, :except => [:new, :show] do
        collection do 
           post :import 
        end
      end
    end
    resources :reports, :protocol => PROTOCOL do
      collection do
        get :usage
        get :dials
        post :dial_details
        post :download
        get :answers
      end
    end
    get '/deleted_campaigns', :to => 'broadcast/campaigns#deleted', :as => :broadcast_deleted_campaigns
    resources :scripts
    resources :messages
    match 'monitor', :to => 'monitor#index'
    match '/', :to => 'broadcast#index', :as => 'broadcast_root'
    match '/login', :to => 'broadcast#login', :as => 'broadcast_login'
  end

  namespace 'broadcast' do
    resources :campaigns, :only => [:show, :index]
  end

  namespace 'client' do
    [:campaigns, :scripts, :callers].each do |type_plural|
      get "/deleted_#{type_plural}", :to => "#{type_plural}#deleted", :as => "deleted_#{type_plural}"
      resources type_plural, :only => [:new, :index, :show, :destroy, :create, :update] do
        put 'restore', :to => "#{type_plural}#restore"
      end
    end
    resources :callers do
      member{ get :reassign_to_campaign }
    end
    resources :campaigns, :only => [] do
      resources :reports do
        collection do
          get :download_report
          post :download
        end
      end
    end
    resource :account, :only => [:show, :create]
    resources :reports do
      collection do
        get :usage
        get :answer
        get :dials
      end
    end
    get :update_report_real
    resources :users, :only => [:create, :destroy]
    post 'user_invite', :to => 'users#invite', :as => 'user_invite'
  end

  scope 'client' do
    match '/', :to => 'client#index', :as => 'client_root'
    resources :campaigns, :only => [] do
      member { post :verify_callerid }
      resources :voter_lists, :except => [:new, :show, :index], :name_prefix => 'client' do
        collection { post :import }
      end
    end
    resources :blocked_numbers, :only => [:index, :create, :destroy]
    resources :monitors do
      collection do
        get :start
        get :stop
        get :deactivate_session
        get :switch_mode
        get :monitor_session
      end
      match "toggle_call_recording" => "monitors#toggle_call_recording"
    end
  end

  scope 'caller' do
    match '/', :to => 'caller#index', :as => 'caller_root'
    match 'logout', :to => 'caller#logout', :as => 'caller_logout'
  end

  resources :campaigns, :path_prefix => 'client', :only => [] do
    member { post :verify_callerid }
    resources :voter_lists, :collection => {:import => :post}, :except => [:new, :show], :name_prefix => 'client'
    match 'clear_calls', :to => 'client/campaigns#clear_calls', :as => 'clear_calls'
  end

  resources :call_attempts, :protocol => PROTOCOL, :only => [:create, :update] do
    member do
      post :connect
      post :end
      post :disconnect
      post :voter_response
      post :hangup
    end
  end
  
  resources :transfer, :protocol => PROTOCOL do
    member do
      post :connect
      post :end
      post :disconnect      
    end
    collection do 
      post :callee
      post :caller            
      post :dial
    end
  end
  

  resources :users do
    put '/update_password', :to => 'client/users#update_password', :as => 'update_password'
  end

  get '/reset_password', :to => 'client/users#reset_password', :as => 'reset_password'

  match '/client/login', :to => 'client#login', :as => :login
  match '/caller/login', :to => 'caller#login', :as => :caller_login

  match '/client/reports', :to => 'client#reports', :as => 'report', :protocol => PROTOCOL
  match '/twilio_callback', :to => 'twilio#callback', :as => :twilio_callback, :protocol => PROTOCOL
  match '/twilio_report_error', :to => 'twilio#report_error', :as => :twilio_report_error, :protocol => PROTOCOL
  match '/twilio_call_ended', :to => 'twilio#call_ended', :as => :twilio_call_ended, :protocol => PROTOCOL

  get 'admin/status', :to => 'admin#state'

  resource :call_attempts, :only => :create

  match ':controller/:action/:id'
  match ':controller/:action'
end

app/models/campaign.rb
require Rails.root.join("lib/twilio_lib")

class Campaign < ActiveRecord::Base
  include Deletable
  include ApplicationHelper::TimeUtils
  include ReportsHelper::Utilization
  include ReportsHelper::Billing

  has_many :caller_sessions
  has_many :voter_lists, :conditions => {:active => true}
  has_many :all_voters, :class_name => 'Voter'
  has_many :call_attempts
  has_many :transfer_attempts
  has_many :callers
  has_one :simulated_values
  has_many :answers
  has_many :call_responses
  belongs_to :script
  belongs_to :voicemail_script, :class_name => 'Script', :foreign_key => 'voicemail_script_id'
  belongs_to :account
  belongs_to :recording

  scope :robo, :conditions => {:robo => true}
  scope :manual, :conditions => {:robo => false}
  scope :for_account, lambda { |account| {:conditions => ["account_id = ?", account.id]} }
  scope :with_running_caller_sessions, {
      :select => "distinct campaigns.*",
      :joins => "inner join caller_sessions on (caller_sessions.campaign_id = campaigns.id)",
      :conditions => {"caller_sessions.on_call" => true}
  }
  scope :using_web_ui, :conditions => {:use_web_ui => true}

  before_create :create_uniq_pin

  attr_accessor :predictive_alpha, :predictive_beta

  validates :name, :presence => true
  validates :caller_id, :presence => true, :unless => :new_campaign
  validates :caller_id, :numericality => {:on => :update}, :length => {:on => :update, :minimum => 10, :maximum => 10}, :unless => Proc.new{|campaign| campaign.caller_id && campaign.caller_id.start_with?('+')}
  validate :set_caller_id_error_msg
  validate :predictive_type_change
  cattr_reader :per_page
  @@per_page = 25

  before_validation :set_untitled_name
  before_save :set_untitled_name
  #before_save :set_answering_machine_detect
  before_validation :sanitize_caller_id

  module Type
    PREVIEW = "preview"
    PREDICTIVE = "algorithm1"
    PROGRESSIVE = "progressive"
  end

  def new_campaign
    new_record?
  end

  def set_caller_id_error_msg
      if errors[:caller_id].any?
        errors.add(:base, 'Your Caller ID must be a 10-digit North American phone number or begin with "+" and the country code.')
        errors[:caller_id].clear
      end
    end

  def set_caller_id_error_msg
    if errors[:caller_id].any?
      errors.add(:base, 'Your Caller ID must be a 10-digit North American phone number or begin with "+" and the country code.')
      errors[:caller_id].clear
    end
  end

  def predictive_type_change
    if predictive_type_changed? && callers_log_in?
      errors.add(:base, 'You cannot change dialing modes while callers are logged in.')
    end
  end


  def predictive_type_change
     if predictive_type_changed? && callers_log_in?
       errors.add(:base, 'You cannot change dialing modes while callers are logged in.')
     end
   end

  def is_preview_or_progressive
    predictive_type == Type::PREVIEW || predictive_type == Type::PROGRESSIVE
  end

  def set_untitled_name
    self.name = "Untitled #{account.campaigns.count + 1}" if self.name.blank?
  end

  def sanitize_caller_id
    self.caller_id = Voter.sanitize_phone(self.caller_id)
  end

  def create_uniq_pin
    pin = nil

    loop do
      pin = rand.to_s[2..6]
      break unless Campaign.find_by_campaign_id(pin)
    end
    self.campaign_id = pin
  end

  def set_answering_machine_detect
    self.answering_machine_detect = self.use_recordings = self.robo? && !self.voicemail_script.nil?
  end

  def disable_voter_list
    voter_lists.each do |voter_list|
      voter_list.enabled = false
      voter_list.save
    end
  end

  def leave_voicemail?
     self.robo? && self.voicemail_script
  end

  def time_period_exceed?
    if start_time.hour < end_time.hour
      !(start_time.hour <= Time.now.utc.in_time_zone(time_zone).hour && end_time.hour > Time.now.utc.in_time_zone(time_zone).hour)
    else
      !(start_time.hour >= Time.now.utc.in_time_zone(time_zone).hour || end_time.hour < Time.now.utc.in_time_zone(time_zone).hour)
    end
  end

  def oldest_available_caller_session
    caller_sessions.available.find(:first, :order => "updated_at ASC", :lock => true)
  end

  def recent_attempts(mins=10)
    attempts = CallAttempt.find_all_by_campaign_id(self.id, :conditions=>"call_start > DATE_SUB(now(),INTERVAL #{mins} MINUTE)", :order=>"id desc")
  end

  def callers_log_in?
    caller_sessions.on_call.length > 0
  end

  def end_all_calls(account, auth, appurl)
    in_progress = CallAttempt.find_all_by_campaign_id(self.id, :conditions=>"sid is not null and call_end is null and id > 45")
    in_progress.each do |attempt|
      t = TwilioLib.new(account, auth)
      a=t.call("POST", "Calls/#{attempt.sid}", {'CurrentUrl'=>"#{appurl}/callin/voterEndCall?attempt=#{attempt.id}"})
      attempt.call_end=Time.now
      attempt.save
    end
    in_progress
  end

  def end_all_callers(account, auth, appurl)
    in_progress = CallerSession.find_all_by_campaign_id(self.id, :conditions=>"on_call=1")
    in_progress.each do |caller|
      t = TwilioLib.new(account, auth)
      a=t.call("POST", "Calls/#{caller.sid}", {'CurrentUrl'=>"#{appurl}/callin/callerEndCall?session=#{caller.id}"})
      if a.index("RestException")
        caller.on_call=false
        caller.save
      end
    end
    in_progress
  end

  def calls_in_ending_window(period=10, predictive_type="longest")
    #calls predicted to end soon
    stats = self.call_stats(period)
    if predictive_type=="longest"
      window = stats[:biggest_long]
    else
      window = stats[:avg_long]
    end
    window = window - 10 if window > 10
#   Rails.logger.debug("window: #{window}")
    ending = CallAttempt.all(:conditions=>"
    campaign_id=#{self.id}
    and status like'Connected to caller%'
    and timediff(now(),call_start) >SEC_TO_TIME(#{window})
    ")
    ending
  end

  def call_stats(mins=nil)
    @stats ||= {:attempts=>[], :abandon=>0, :answer=>0, :no_answer=>0,
                :total=>0, :answer_pct=>0, :avg_duration=>0, :abandon_pct=>0,
                :avg_hold_time=>0, :total_long=>0, :total_short=>0, :avg_long=>0,
                :biggest_long=>0, :avg_ring_time=>0, :avg_ring_time_devation=>0,
                :current_short=>0, :current_long=>0,
                :short_deviation=>0, :avg_short=>0}.tap do |stats|
      totduration=0
      tothold=0
      totholddata=0
      totlongduration=0
      totshortduration=0
      totringtime=0
      totringattempts=0
      ringattempts=[]
      longattempts=[]
      shortattempts=[]
      stats[:short_time] = 15

      if mins.blank?
        attempts = CallAttempt.find_all_by_campaign_id(self.id, :order=>"id desc")
      else
        attempts = CallAttempt.find_all_by_campaign_id(self.id,:conditions=>"call_start > DATE_SUB(now(),INTERVAL #{mins} MINUTE) or call_end > DATE_SUB(now(),INTERVAL #{mins} MINUTE)", :order=>"id desc")
      end

      stats[:attempts]=attempts

      attempts.each do |attempt|

        if attempt.status=="Call completed with success." || attempt.status.index("Connected to") #  || attempt.status=="Call in progress"
          stats[:answer] = stats[:answer]+1
          if attempt.ring_time!=nil
            totringtime=totringtime+attempt.ring_time
            totringattempts+=1
            ringattempts << attempt.ring_time
          end
        elsif attempt.status=="Call abandoned"
          stats[:abandon] = stats[:abandon]+1
        else
          stats[:no_answer] = stats[:no_answer]+1
        end

        stats[:total] = stats[:total]+1

        if attempt.status.index("Connected to") && attempt.duration!=nil
          if attempt.duration > stats[:short_time]
            stats[:current_long]=stats[:current_long]+1
          else
            stats[:current_short]=stats[:current_short]+1
          end
        end


        if attempt.duration!=nil && attempt.duration>0
          totduration = totduration + attempt.duration
          if attempt.duration <= stats[:short_time]
            stats[:total_short] = stats[:total_short]+1
            totshortduration = totshortduration + attempt.duration
            shortattempts<<attempt.duration.to_i
          else
            stats[:total_long] = stats[:total_long]+1
            totlongduration = totlongduration + attempt.duration
            longattempts<<attempt.duration.to_i
            stats[:biggest_long] = attempt.duration if attempt.duration > stats[:biggest_long]
          end
        end

        if !attempt.caller_hold_time.blank?
          tothold = tothold + attempt.caller_hold_time
          totholddata+=1
        end
      end
      #    avg_hold_time
      stats[:answer_pct] = (stats[:answer].to_f + stats[:abandon].to_f)/ stats[:total].to_f if stats[:total] > 0
      stats[:abandon_pct] = stats[:abandon].to_f / (stats[:answer].to_f + stats[:abandon].to_f) if stats[:answer] > 0
      stats[:avg_duration] = totduration / stats[:answer].to_f if stats[:answer] > 0
      stats[:avg_hold_time] = tothold/ totholddata if totholddata> 0
      stats[:avg_long] = totlongduration / stats[:total_long] if stats[:total_long] > 0
      stats[:avg_short] = totshortduration / stats[:total_short] if stats[:total_short] > 0
      stats[:avg_ring_time] = totringtime/totringattempts if totringattempts >0
      stats[:avg_ring_time_deviation] = self.std_deviation(ringattempts)
      stats[:long_deviation] = self.std_deviation(longattempts)
      stats[:short_deviation] = self.std_deviation(shortattempts)
      stats[:answer_plus_abandon_ct] = (stats[:abandon].to_f + stats[:answer].to_f) / stats[:total].to_f if stats[:total] > 0


      #new algo stuff
      if stats[:answer_plus_abandon_ct] ==nil
        stats[:dials_needed] = 2
      else
        dials = 1 / stats[:answer_plus_abandon_ct]
        dials = 2 if dials.infinite?
        dials = dials.to_f.round
        dials = self.max_calls_per_caller if dials > self.max_calls_per_caller
        dials = 2 if attempts.length < 50
        #      dials=1
        stats[:dials_needed] = dials
      end

app/controllers/client/accounts_controller.rb
module Client
  class AccountsController < ClientController
    def show
    end
  end
end

app/helpers/campaign_helper.rb
module CampaignHelper
  
  def am_pm_hour_select(field_name)
    select_tag(field_name,options_for_select([
        ["1 AM", "01"],["2 AM", "02"],["3 AM", "03"],["4 AM", "04"],["5 AM", "05"],["6 AM", "06"],
        ["7 AM", "07"],["8 AM", "08"],["9 AM", "09"],["10 AM", "10"],["11 AM", "11"],["Noon", "12"],
        ["1 PM", "13"],["2 PM", "14"],["3 PM", "15"],["4 PM", "16"],["5 PM", "17"],["6 PM", "18"],
        ["7 PM", "19"],["8 PM", "20"],["9 PM", "21"],["10 PM", "22"],["11 PM", "23"],["Midnight", "0"]]))
  end
   
  def hours
    [["1 AM", "1"],["2 AM", "2"],["3 AM", "3"],["4 AM", "4"],["5 AM", "5"],["6 AM", "6"],
    ["7 AM", "7"],["8 AM", "8"],["9 AM", "9"],["10 AM", "10"],["11 AM", "11"],["Noon", "12"],
    ["1 PM", "13"],["2 PM", "14"],["3 PM", "15"],["4 PM", "16"],["5 PM", "17"],["6 PM", "18"],
    ["7 PM", "19"],["8 PM", "20"],["9 PM", "21"],["10 PM", "22"],["11 PM", "23"],["Midnight", "0"],]
  end
  
end

app/helpers/client_helper.rb
module ClientHelper
  def callerInCampaign(c)
    @campaign && @campaign.callers.include?(c)
  end

  def listInCampaign(c)
    @campaign && @campaign.voter_lists.include?(c)
  end

  def logged_in_as_client?
    session[:user] && @user
  end

  def logged_in_as_caller?
    session[:caller] && @caller
  end
end

app/views/client/campaigns/_voicemail.html.erb
<% form||=nil %>
<p><%= form.check_box :answering_machine_detect %>&nbsp;Automatically detect voicemails</p>
<% if !@campaign.account.recordings.blank? %>
    <p><%= form.check_box :use_recordings, :onclick=>"doRecord();" %>&nbsp;Leave voicemail message</p>

    <div id="recordingsdiv"
         <% if  !@campaign.use_recordings? %> style="display:none;"
         <% end %>>
      <label for=""><p>Voicemail</label><br>
      <%= form.collection_select(:recording_id, @account.recordings.active, :id, :name, {:prompt => false}, {:class=>"field", :onchange=>"updatePreview();"}) %></p>
      <div id="sndPreview"></div>
    </div>
<% end %>

<p class="actions">
  <a href='/client/recording_add?campaign_id=<%= @campaign.id %>' class="action secondary">Add voicemail message</a>
</p>

app/views/client/campaigns/index.html.erb
<% content_for :javascripts do %>
  <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.js" %>
<% end %>

<h1>Campaigns</h1>
<% if @campaigns.length==0 %>
  <div class="form">
    <label>No campaigns entered.</label>
  </div>
<% else %>
  <table>
    <tr>
      <th>Name</th>
      <th>Date added</th>
      <th width="55" class="ac"></th>
    </tr>
    <% @campaigns.each do |c| %>
      <tr class="<%= cycle("odd","even") %>">
        <td><strong><%= link_to c.name, c %></strong></td>
        <td><%= c.created_at.strftime("%m/%d/%Y") %></td>
        <td>
          <%= form_tag campaign_path(c), :method => 'delete', :id => "campaign_delete_form_#{c.id}" do %>
            <%= link_to 'Delete', 'javascript:void(0)', :class => 'ico del', :onclick => "delete_entity('#campaign_delete_form_#{c.id}')" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
  <p><%= page_entries_info @campaigns %> <%= will_paginate @campaigns %></p>
<% end %>

<p class="actions">
    <%= link_to 'Add new campaign', new_client_campaign_path, :class => 'action primary' %>
</p>
<p class="actions"><%= link_to 'View deleted campaigns', @deleted_campaigns_path, :class => 'action secondary' %></p>

app/views/client/campaigns/show.html.erb
<% content_for :javascripts do %>
    <%= javascript_include_tag "campaign/auto_save" %>
    <%= javascript_include_tag "campaign/campaign" %>
<% end %>
<h1>Edit campaign</h1>
<div id="callerid"></div>

<%= form_for @campaign, url: "#{client_campaigns_path}/#{@campaign.id}", :method=> :put, :html => {:name => 'callerForm', :id => 'callerForm'} do |f| %>
    <div id="validationError">
      <%= render "shared/error_messages", :target => @campaign %>
    </div>
    <fieldset>

      <%= hidden_field_tag :id, @campaign.id, {:class=>"field"} %>
      <legend>Campaign options</legend>
      <fieldset>
        <legend>Basic settings</legend>
        <p><label for="">Name</label><br>
          <%= f.text_field :name, {:class=>"field size3"} %></p>

        <p><label for="">Caller ID</label><br>
          <%= f.text_field :caller_id, {:class=>"field size3"} %></p>

        <p><label for="">Script</label><br>
          <%= f.collection_select(:script_id, @scripts, :id, :name, {:class=>"field"}) %>
        </p>

        <p><label for="">Dialing mode</label>
          <select class="field" id="campaign_predictive_type" name="campaign[predictive_type]" onchange="dialingModeOnChange()">
            <% public_dialers = [["Predictive", "algorithm1"], ["Power", "progressive"], ["Preview", "preview"],] %>
            <% if !public_dialers.map { |pair| pair[1] }.index(@campaign.predictive_type) %>
                <option value="<%= @campaign.predictive_type %>" selected><%= @campaign.predictive_type %></option>
            <% end %>
            <%= options_for_select public_dialers, @campaign.predictive_type %>
          </select>
        </p>
        <div id="abandon_rate_edit" style="display: none">
          <p><label>Abandonment rate</label>
            <select class="field" id="campaign_abandon_rate" name="campaign[acceptable_abandon_rate]">
              <%= options_for_select [["1%", 0.01], ["2%", 0.02], ["3%", 0.03]], @campaign.acceptable_abandon_rate %>
            </select>
          </p>
        </div>

        <p><label for="">Time zone</label>
          <%= time_zone_select("campaign", 'time_zone', ActiveSupport::TimeZone.us_zones, :default => "Pacific Time (US & Canada)") %>
        </p>

        <p><label for="">Dialing hours</label>
          <select class="field" id="campaign_start_time" name="campaign[start_time]">

            <% if @campaign.start_time %>
                <option value="<%= @campaign.start_time.try(:hour) %>" selected>
                  <%= hours.map { |p| p[0] }[hours.map { |pair| pair[1] }.index(@campaign.start_time.try(:hour).to_s)] %>
                </option>
            <% end %>
            <%= options_for_select hours, @campaign.start_time %>
          </select>
          to
          <select class="field" id="campaign_end_time" name="campaign[end_time]">

            <% if @campaign.end_time %>
                <option value="<%= @campaign.end_time.try(:hour) %>" selected>
                  <%= hours.map { |p| p[0] }[hours.map { |pair| pair[1] }.index((@campaign.end_time.try(:hour)).to_s)] %>
                </option>
            <% end %>
            <%= options_for_select hours, @campaign.end_time %>
          </select>
        </p>

        <%= render :partial => 'shared/recycle_rate', :locals => {:recycle_hour => @campaign.recycle_rate} %>
        <%= render :partial => 'voicemail', :locals => {:form => f} %>
      </fieldset>

      <fieldset>
        <legend>Lists being called</legend>
        <% if @lists.length==0 %>
            <p>You haven't uploaded any lists yet.</p>
        <% else %>
            <table>
              <tr>
                <th>Name</th>
                <th>Phone #s</th>
                <th>Remaining</th>
              </tr>
              <% @lists.each do |l| %>
                  <tr>
                    <td valign="top"><%= check_box_tag "voter_list_ids[]", "#{l.id}", l.enabled -%> <%= l.name %></td>
                    <td valign="top"><%= l.voters.size %></td>
                    <td valign="top"><%= Voter.remaining_voters_count_for('voter_list_id', l.id) %></td>
                  </tr>
              <% end %>
            </table>
        <% end %>
      </fieldset>
      <div class="buttons">
        <button type="submit">Save</button>
      </div>
    </fieldset>
<% end %>
<fieldset>
  <legend>Add list</legend>
  <%= render :partial => "voter_lists/new", :locals => {:path => campaign_client_voter_lists_path(@campaign)} %>
</fieldset>

<script>
    function dialingModeOnChange() {
        var dialMode = $('#campaign_predictive_type').val();
        if (dialMode == "algorithm1") {
            $('#abandon_rate_edit').show();
            $('#campaign_abandon_rate').val(0.03);
        } else {
            $('#abandon_rate_edit').hide();
        }
    }

    $(function () {
        if ($("#campaign_predictive_type").val() == "algorithm1") {
            $("#abandon_rate_edit").show();

        }
        if ($('#callers input[name^= "campaign[caller_ids]"]:checked').length == <%= @callers.length %>) {
            $('#selectAll').attr('checked', true)
        }

        $('#selectAll').click(function () {
            $('#callers').find(':checkbox').attr('checked', this.checked);
        });

        $('#callers input[name^= "campaign[caller_ids]"]').change(function() {
            if ($('#callers input[name^= "campaign[caller_ids]"]:checked').length == <%= @callers.length %>) {
                $('#selectAll').attr('checked', true)
            }
            if ($('#callers input[name^= "campaign[caller_ids]"]:checked').length < <%= @callers.length %>) {
                $('#selectAll').attr('checked', false)
            }
        });

        $('#campaign_answering_machine_detect').click(function () {
            if ($('#campaign_answering_machine_detect').attr('checked') == false) {

                if ($("#campaign_use_recordings").attr('checked') == true) {
                    $("#recordingsdiv").toggle($("#campaign_use_recordings").checked);
                    $("#campaign_use_recordings").attr('checked', false);
                }
            }
        });

    });

    <% if !@campaign.account.recordings.blank? %>
    function updatePreview() {
        recording_id = $("#campaign_recording_id").val();
    <%@account.recordings.each do |recording| %>
        if (recording_id ==<%= recording.id %>) {
            path = '<%= recording.file.url %>';
            name = '<%= escape_javascript recording.name %>';
        }
    <% end %>

        var o = 'Preview: ' + name + '<br/>';

        if (path.indexOf('mp3') > -1)
            o = o + '<object type="application/x-shockwave-flash" width="200" height="14" data="/xspf_player_slim.swf?player_title=' + name + '&song_title=' + name + '&song_url=' + escape(path) + '"><param name="movie" value="/xspf_player_slim.swf?player_title=' + name + '&song_title=' + name + '&song_url=' + escape(path) + '" /></object>';
        else
            o = o + '<EMBED SRC="' + path + '" WIDTH="240" HEIGHT = "25" AUTOPLAY="false" CONTROLLER="true" LOOP="false" PLUGINSPAGE="http://www.apple.com/quicktime/">';
        $('sndPreview').innerHTML = o;
    }
    <% end %>
    updatePreview();
</script>

app/views/client/campaigns/update.js.erb
<%= render "shared/error_messages", :target => @campaign %>