config/routes.rb
PROTOCOL = Rails.env == 'development' || Rails.env == 'heroku_staging' ? 'http://' : 'https://'

ImpactDialing::Application.routes.draw do
  root :to => "home#index"

  ['monitor', 'how_were_different', 'pricing', 'contact', 'policies'].each do |path|
    match "/#{path}", :to => "home##{path}", :as => path
  end
  match '/client/policies', :to => 'client#policies', :as => :client_policies
  match '/broadcast/policies', :to => 'broadcast#policies', :as => :broadcast_policies
  match '/homecss/css/style.css', :to => 'home#homecss'
  
  namespace 'api' do
    resources :leads
    resources :callers
  end

  namespace 'admin' do
    [:campaigns, :scripts, :callers].each do |entities|
      resources entities, :only => [:index] do
        put '/restore', :controller => entities, :action => 'restore', :as => 'restore'
      end
    end
  end

  namespace "callers" do
    resources :campaigns do
      member do
        post :callin
        match :caller_ready
      end
    end
  end

  resources :caller, :protocol => PROTOCOL, :only => [:index] do
    collection do
      get :login
      post :end_session
      post :phones_only
    end

    member do
      post :assign_campaign
      post :pause
      post :active_session
      post :preview_voter
      post :skip_voter
      post :call_voter
      post :stop_calling
      post :start_calling
      post :gather_response
      post :choose_voter
      post :phones_only_progressive
      post :choose_instructions_option
      post :check_reassign
      post :kick_caller_off_conference
      post :new_campaign_response_panel
      post :transfer_panel
    end

  end

  post :receive_call, :to => 'callin#create', :protocol => PROTOCOL
  post :end_caller_session, :to =>'caller/end_session'
  post :identify_caller, :to => 'callin#identify', :protocol => PROTOCOL
  get :hold_call, :to => 'callin#hold', :protocol => PROTOCOL

  #broadcast
  scope 'broadcast', :protocol => PROTOCOL do
    resources :campaigns do
      member do
        post :verify_callerid
        post :start
        post :stop
        get :dial_statistics
      end
      collection do
        get :control
        get :running_status
      end
      resources :voter_lists, :except => [:new, :show] do
        collection do 
           post :import 
        end
      end
    end
    resources :reports, :protocol => PROTOCOL do
      collection do
        get :usage
        get :dials
        post :dial_details
        post :download
        get :answers
      end
    end
    get '/deleted_campaigns', :to => 'broadcast/campaigns#deleted', :as => :broadcast_deleted_campaigns
    resources :scripts
    resources :messages
    match 'monitor', :to => 'monitor#index'
    match '/', :to => 'broadcast#index', :as => 'broadcast_root'
    match '/login', :to => 'broadcast#login', :as => 'broadcast_login'
  end

  namespace 'broadcast' do
    resources :campaigns, :only => [:show, :index]
  end

  namespace 'client' do
    [:campaigns, :scripts, :callers].each do |type_plural|
      get "/deleted_#{type_plural}", :to => "#{type_plural}#deleted", :as => "deleted_#{type_plural}"
      resources type_plural, :only => [:new, :index, :show, :destroy, :create, :update] do
        put 'restore', :to => "#{type_plural}#restore"
      end
    end
    resources :callers do
      member{ get :reassign_to_campaign }
    end
    resources :campaigns, :only => [] do
      resources :reports do
        collection do
          get :download_report
          post :download
        end
      end
    end
    resource :account, :only => [:show, :create]
    resources :reports do
      collection do
        get :usage
        get :answer
        get :dials
      end
    end
    get :update_report_real
    resources :users, :only => [:create, :destroy]
    post 'user_invite', :to => 'users#invite', :as => 'user_invite'
  end

  scope 'client' do
    match '/', :to => 'client#index', :as => 'client_root'
    resources :campaigns, :only => [] do
      member { post :verify_callerid }
      resources :voter_lists, :except => [:new, :show, :index], :name_prefix => 'client' do
        collection { post :import }
      end
    end
    resources :blocked_numbers, :only => [:index, :create, :destroy]
    resources :monitors do
      collection do
        get :start
        get :stop
        get :deactivate_session
        get :switch_mode
        get :monitor_session
      end
      match "toggle_call_recording" => "monitors#toggle_call_recording"
    end
  end

  scope 'caller' do
    match '/', :to => 'caller#index', :as => 'caller_root'
    match 'logout', :to => 'caller#logout', :as => 'caller_logout'
  end

  resources :campaigns, :path_prefix => 'client', :only => [] do
    member { post :verify_callerid }
    resources :voter_lists, :collection => {:import => :post}, :except => [:new, :show], :name_prefix => 'client'
    match 'clear_calls', :to => 'client/campaigns#clear_calls', :as => 'clear_calls'
  end

  resources :call_attempts, :protocol => PROTOCOL, :only => [:create, :update] do
    member do
      post :connect
      post :end
      post :disconnect
      post :voter_response
      post :hangup
    end
  end
  
  resources :transfer, :protocol => PROTOCOL do
    member do
      post :connect
      post :end
      post :disconnect      
    end
    collection do 
      post :callee
      post :caller            
      post :dial
    end
  end
  

  resources :users do
    put '/update_password', :to => 'client/users#update_password', :as => 'update_password'
  end

  get '/reset_password', :to => 'client/users#reset_password', :as => 'reset_password'

  match '/client/login', :to => 'client#login', :as => :login
  match '/caller/login', :to => 'caller#login', :as => :caller_login

  match '/client/reports', :to => 'client#reports', :as => 'report', :protocol => PROTOCOL
  match '/twilio_callback', :to => 'twilio#callback', :as => :twilio_callback, :protocol => PROTOCOL
  match '/twilio_report_error', :to => 'twilio#report_error', :as => :twilio_report_error, :protocol => PROTOCOL
  match '/twilio_call_ended', :to => 'twilio#call_ended', :as => :twilio_call_ended, :protocol => PROTOCOL

  get 'admin/status', :to => 'admin#state'

  resource :call_attempts, :only => :create

  match ':controller/:action/:id'
  match ':controller/:action'
end

app/controllers/client/reports_controller.rb
module Client
  class ReportsController < ClientController
    before_filter :load_campaign, :except => [:index, :usage]
    before_filter :set_report_date_range, :only => [:usage]

    def load_campaign
      @campaign = Campaign.find(params[:campaign_id])
    end

    def index
      @campaigns = params[:id].blank? ? account.campaigns.manual : Campaign.find(params[:id])
      @callers = account.callers
    end
    
    def dials
      set_date_range

      dialed_voters = @campaign.all_voters.last_call_attempt_within(@from_date, @to_date)
      @total_voters_count = @campaign.all_voters.count
      dialed_voters_ids = dialed_voters.collect{|x| x.id} 
      if dialed_voters
        @answered = @campaign.answered_count(dialed_voters_ids)
        @no_answer = dialed_voters.by_status(CallAttempt::Status::NOANSWER).count
        @busy_signal = dialed_voters.by_status(CallAttempt::Status::BUSY).count
        @answering_machine = dialed_voters.by_status(CallAttempt::Status::HANGUP).count
        @voicemail = dialed_voters.by_status(CallAttempt::Status::VOICEMAIL).count
        @ringing = dialed_voters.by_status(CallAttempt::Status::RINGING).count
        @abandoned = dialed_voters.by_status(CallAttempt::Status::ABANDONED).count
        @failed = dialed_voters.by_status(CallAttempt::Status::FAILED).count
        @scheduled = dialed_voters.by_status(CallAttempt::Status::SCHEDULED).count
      end
      @total = ((@total_voters_count == 0) ? 1 : @total_voters_count)
      @ready_to_dial = params[:from_date] ? 0 : @campaign.all_voters.by_status(CallAttempt::Status::READY).count
      @not_dialed = not_dilaed_voters(params[:from_date])
      @total_dials = @answered.to_i + @no_answer.to_i + @busy_signal.to_i + @ringing.to_i + @abandoned.to_i + @failed.to_i + @voicemail.to_i + @scheduled.to_i + @answering_machine.to_i
    end

    def usage
      @campaign = current_user.campaigns.find(params[:id])
    end
    
    def download_report
      set_date_range
      @voter_fields = VoterList::VOTER_DATA_COLUMNS
      @custom_voter_fields = @user.account.custom_voter_fields.collect{ |field| field.name}      
    end

    def download
      set_date_range
      Delayed::Job.enqueue ReportJob.new(@campaign, @user, params[:voter_fields], params[:custom_voter_fields], params[:download_all_voters], @from_date, @to_date)
      flash_message(:notice, I18n.t(:client_report_processing))
      redirect_to client_reports_url
    end

    def answer
      set_date_range
      @results = @campaign.answers_result(@from_date, @to_date)
      @transfers = @campaign.transfers(@from_date, @to_date)
    end

    private
    
    def set_date_range
      time_zone = ActiveSupport::TimeZone.new(@campaign.time_zone || "UTC")
      from_date = Time.strptime("#{params[:from_date]} #{time_zone.formatted_offset}", "%m/%d/%Y %:z") if params[:from_date]
      to_date = Time.strptime("#{params[:to_date]} #{time_zone.formatted_offset}", "%m/%d/%Y %:z") if params[:to_date]
      @from_date = (from_date || @campaign.call_attempts.first.try(:created_at) || Time.now).in_time_zone(time_zone).beginning_of_day
      @to_date = (to_date || @campaign.call_attempts.last.try(:created_at) || Time.now).in_time_zone(time_zone).end_of_day
    end
    
    def not_dilaed_voters(range_parameters)
      if range_parameters
        @total_voters_count - (@answered.to_i + @no_answer.to_i + @busy_signal.to_i + @ringing.to_i + @abandoned.to_i + @failed.to_i + @voicemail.to_i + @scheduled.to_i + @answering_machine.to_i)
      else
        @campaign.all_voters.by_status(Voter::Status::NOTCALLED).count
      end
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ClientController
  layout 'v2'
  before_filter :load_campaign, :only => [:usage, :dials, :answers]

  def load_campaign
    @campaign = Campaign.find(params[:campaign_id])
  end
  
  def index
    @campaigns = account.campaigns.robo.active
  end

  def usage
    @minutes = @campaign.call_attempts.for_status(CallAttempt::Status::SUCCESS).inject(0) { |sum, ca| sum + ca.minutes_used }
  end
  
  def answers
    set_report_period
    @results = @campaign.robo_answer_results(@from_date, @to_date)
    render :template => 'client/reports/answer'
  end
  
  def dials
    set_report_period
    
    dialed_voters = @campaign.all_voters.last_call_attempt_within(@from_date, @to_date)
    @total_voters = @campaign.all_voters
    if dialed_voters
      @answered = dialed_voters.by_status(CallAttempt::Status::ANSWERED).count
      @no_answer = dialed_voters.by_status(CallAttempt::Status::NOANSWER).count
      @busy_signal = dialed_voters.by_status(CallAttempt::Status::BUSY).count
      @answering_machine = dialed_voters.by_status(CallAttempt::Status::HANGUP).count
      @voicemail = dialed_voters.by_status(CallAttempt::Status::VOICEMAIL).count
      @ringing = dialed_voters.by_status(CallAttempt::Status::RINGING).count
      @failed = dialed_voters.by_status(CallAttempt::Status::FAILED).count
    end
    @total = ((@total_voters.count == 0) ? 1 : @total_voters.count)
    @not_dialed = not_dilaed_voters(params[:from_date])
    @total_dials = @answered.to_i + @no_answer.to_i + @busy_signal.to_i + @answering_machine.to_i + @voicemail.to_i + @ringing.to_i + @failed.to_i
  end
  
  def dial_details
    @campaign = account.campaigns.find(params[:id])
    set_report_period
    @voter_fields = VoterList::VOTER_DATA_COLUMNS
    @custom_voter_fields = @user.account.custom_fields.collect{ |field| field.name}    
  end
  
  def download
    @campaign = account.campaigns.find(params[:id])
    set_report_period
    Delayed::Job.enqueue ReportJob.new(@campaign, @user, params[:voter_fields], params[:custom_voter_fields], params[:download_all_voters], @from_date, @to_date)
    flash_message(:notice, I18n.t(:client_report_processing))
    redirect_to reports_url
  end
  
  private
  
  def set_report_period
    from_date = Date.strptime(params[:from_date], "%m/%d/%Y") if params[:from_date]
    to_date = Date.strptime(params[:to_date], "%m/%d/%Y") if params[:to_date]
    @from_date = from_date || (@campaign.call_attempts.first.try(:created_at) || Time.now)
    @to_date = to_date || Time.now
  end
  
  def not_dilaed_voters(range_parameters)
    if range_parameters
      @total_voters.count - (@answered.to_i + @no_answer.to_i + @busy_signal.to_i + @ringing.to_i + @failed.to_i + @answering_machine.to_i + @voicemail.to_i)
    else
      @total_voters.by_status(Voter::Status::NOTCALLED).count
    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper

  module Utilization
    def time_logged_in(from, to)
      @time_logged_in ||= self.caller_sessions.between(from, to + 1.day).sum('TIMESTAMPDIFF(SECOND ,starttime,endtime)')
      round_for_utilization(@time_logged_in)
    end

    def time_on_call(from, to)
      @time_on_call ||= self.call_attempts.between(from, to + 1.day).without_status([CallAttempt::Status::VOICEMAIL, CallAttempt::Status::ABANDONED]).sum('TIMESTAMPDIFF(SECOND ,connecttime,call_end)')
      round_for_utilization(@time_on_call)
    end

    def time_in_wrapup(from, to)
      @time_in_wrapup ||= self.call_attempts.between(from, to + 1.day).without_status([CallAttempt::Status::VOICEMAIL, CallAttempt::Status::ABANDONED]).sum('TIMESTAMPDIFF(SECOND ,call_end,wrapup_time)')
      round_for_utilization(@time_in_wrapup)
    end

    def time_onhold(from, to)
      time_logged_in(from, to)
      time_on_call(from, to)
      time_in_wrapup(from, to)
      round_for_utilization(@time_logged_in.to_f - @time_on_call.to_f - @time_in_wrapup.to_f)
    end
  end

  module Billing
    def caller_time(from,to)
      self.caller_sessions.between(from, to + 1.day).sum('ceil(TIMESTAMPDIFF(SECOND ,starttime,endtime)/60)').to_i
    end

    def lead_time(from, to)
      self.call_attempts.without_status([CallAttempt::Status::VOICEMAIL, CallAttempt::Status::ABANDONED]).sum('ceil(TIMESTAMPDIFF(SECOND ,connecttime,call_end)/60)').to_i
    end

  end
end

app/views/reports/dial_details.html.erb
<script>
	$(function () {
		$('#download_all_voters_submit').click(function(){
			$('#download_all_voters').attr('checked','checked');
		});
		$('#range_voters_submit').click(function(){
			$('#download_all_voters').removeAttr('checked');
		});
		
		$('#selectAll').click(function () {
		 $('#fields').find(':checkbox').attr('checked', this.checked);
		});

		$('#fields input[name^= "voter_fields[]"]').change(function(){
			set_select_all_checkbox();
		});
		$('#fields input[name^= "custom_voter_fields[]"]').change(function(){
			set_select_all_checkbox();
		});
		function set_select_all_checkbox(){
			var voter_fields_count = $('#fields input[name^= "voter_fields[]"]:checked').length
			var voter_custom_fields_count = $('#fields input[name^= "custom_voter_fields[]"]:checked').length
		  if ((voter_fields_count + voter_custom_fields_count) == <%= (@voter_fields.length + @custom_voter_fields.try(:length)) %> ){
		    $('#selectAll').attr('checked', true)
		  }
		  if ((voter_fields_count + voter_custom_fields_count) < <%= (@voter_fields.length + @custom_voter_fields.try(:length)) %> ){
		    $('#selectAll').attr('checked', false)
		  }
		}
	});
</script>

<h1>Download Report</h1>
<fieldset>
	<div id="fields">
	<legend>Fields to include</legend>
  <% form_tag(download_reports_path(:id => @campaign.id, :protocol => PROTOCOL), :method => "POST") do %>
		<ul>
			<li><input type="checkbox" value="0" id="selectAll">&nbsp;Select all</li>
			<% @voter_fields.try(:each_pair) do |key, value| %>
		    <li>
					<input  type="checkbox" name="voter_fields[]" value="<%= key %>">&nbsp;<%= value %>
		    </li>
		  <% end %>
		<% @custom_voter_fields.try(:each) do |field| %>
	    <li>
				<input  type="checkbox" name="custom_voter_fields[]" value="<%= field %>">&nbsp;<%= field %>
	    </li>
	  <% end %>
		</ul>	
		</div>	
</fieldset>
<input type="checkbox" style="display:none" id="download_all_voters" name="download_all_voters"></input>
<div class="buttons"><button type="submit" id="download_all_voters_submit">Download entire campaign</button></div>

		<h3>Date range:</h3>
		      <table>
		        <tr>
		          <td>From:</td>
		          <td> <%= unobtrusive_date_text_picker_tag :from_date, @from_date %> </td>
		        </tr>
		        <tr>
		          <td>
		            To:
		          </td>
		          <td>  <%= unobtrusive_date_text_picker_tag :to_date, @to_date %>
		          </td>
		        </tr>
		      </table>
		<div class="buttons"><button id="range_voters_submit" type="submit">Download just this date range</button></div>
  <% end %>
</div>

app/views/reports/dials.html.erb
<div class="box" style="width:600px;">
	<%= render :partial => 'shared/boxtop', :locals=>{:title=>"#{@campaign.name} Dials"} %>
	<div class="box-content">
		<div class="table">
		    <table width="100%" border="0" cellspacing="0" cellpadding="0">
		      <tr>
		        <th width="300">Call status</th>
		        <th>Dials</th>
		        <th>Percentage</th>
		      </tr>			
		
					<tr class="<%= cycle("odd","even") %>">
						<td>Answered</td><td><%= @answered %></td><td><%= ((@answered.to_f/@total)*100).round %>%</td>
					</tr>
					<tr class="<%= cycle("odd","even") %>">
						<td>No answer</td><td><%= @no_answer %></td><td><%= ((@no_answer.to_f/@total)*100).round %>%</td>
					</tr>
					<tr class="<%= cycle("odd","even") %>">
						<td>Busy signal</td><td><%= @busy_signal %></td><td><%= ((@busy_signal.to_f/@total)*100).round %>%</td>
					</tr>
					<tr class="<%= cycle("odd","even") %>">
						<td>Answering machine</td><td><%= @answering_machine %></td><td><%= ((@answering_machine.to_f/@total)*100).round %>%</td>
					</tr>
					<tr class="<%= cycle("odd","even") %>">
						<td>Message left</td><td><%= @voicemail %></td><td><%= ((@voicemail.to_f/@total)*100).round %>%</td>
					</tr>
					<tr class="<%= cycle("odd","even") %>">
						<td>Failed</td><td><%= @failed %></td><td><%= ((@failed.to_f/@total)*100).round %>%</td>
					</tr>
					<tr class="<%= cycle("odd","even") %>">
						<td>Ringing</td><td><%= @ringing %></td><td><%= ((@ringing.to_f/@total)*100).round %>%</td>
					</tr>
					<tr class="<%= cycle("odd","even") %>">
						<td>Not dialed</td><td><%= @not_dialed %></td><td><%= ((@not_dialed.to_f/@total)*100).round %>%</td>
					</tr>
					<tr class="<%= cycle("odd","even") %>">
						<td>Total dials</td><td><%= @total_dials %></td><td><%= ((@total_dials.to_f/@total)*100).round %>%</td>
					</tr>
			
		    </table>
		</div>
	</div>
</div>

<h3>Date range:</h3>
<% form_tag(dials_reports_path, :method => :get) do %>
 
  <table>
    <tr>
      <td>From:</td>
      <td> <%= unobtrusive_date_text_picker_tag :from_date,@from_date %> </td>
      </tr>
    <tr>
      <td>To:</td>
      <td>  <%= unobtrusive_date_text_picker_tag :to_date,@to_date %></td>
    </tr>
    </table>
     <input name="campaign_id" type="hidden" value="<%= params[:campaign_id]%>"></input>
  <div class="buttons"><button type="submit">Update date range</button></div>
<% end %>

app/views/reports/index.html.erb
<h1>Reports</h1>
<% if @campaigns.length==0 %>
    <p>You haven't created any campaigns yet.</p>
<% else %>
    <table>
      <tr>
        <th>Campaign</th>
		<th></th>
		<th></th>
		<th></th>
		<th></th>
      </tr>
      <% @campaigns.each do |c| %>
        <tr class="<%= cycle("odd","even") %>">
          <td><%= link_to c.name, campaign_path(c) %></td>
		  		<td><%= link_to 'Dials', dials_reports_path(:campaign_id => c.id) %></td>
					<td><%= link_to 'Answered', answers_reports_path(:campaign_id => c.id) %></td>
          <td><%= link_to 'Usage', usage_reports_path(:campaign_id => c.id) %></td>
          <td><%= link_to "Download", dial_details_reports_path(:id => c.id),:method => "POST" %></td>
        </tr>
      <% end %>
    </table>
<% end %>

app/views/reports/usage.html.erb
<h1>Usage report</h2>
<!--
  <dt>Number of calls</dt>
  <dd><%= @campaign.call_attempts.size %></dd>
-->
  <p>Minutes used: <%= @minutes%></p>